---

- name: Add signing keys for Debian unstable apt repository
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: '{{ item }}'
    state: present
  loop:
    - 0E98404D386FA1D9
    - 648ACFD622F3D138

- name: Add Debian unstable apt repository
  ansible.builtin.apt_repository: 
    repo: 'deb http://deb.debian.org/debian/ unstable main' 
    state: present 
    update_cache: yes

- name: Install OpenSCAP packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ packages }}"

- name: Remove Debian unstable apt repository
  ansible.builtin.apt_repository: 
    repo: 'deb http://deb.debian.org/debian/ unstable main' 
    state: absent